# Generated by Django 4.1.6 on 2023-02-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0002_remove_image_plan_image_image_basic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image_basic",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
