# Generated by Django 4.1.6 on 2023-02-16 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0004_alter_image_image_premium"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="image_basic",
        ),
        migrations.RemoveField(
            model_name="image",
            name="image_premium",
        ),
    ]
